# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - 'VERSION'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo Hello, world!

      # Runs a set of commands using the runners shell
#      - name: Run a multi-line script
 #       run: |
  #        echo Add other actions to build,
   #       echo test, and deploy your project.
          
      - name: Read VERSION
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: VERSION
          trim: True
      - name: Echo VERSION file
        run: echo "..${{ steps.version.outputs.content }}..."
      
      - name: Check tag
        uses: mukunku/tag-exists-action@v1.0.0
        id: checkTag
        with: 
          tag: "${{ steps.version.outputs.content }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: echo ${{ steps.checkTag.outputs }}
#  work:
#    needs: check
 #     - name: Create Tag
  #      uses: negz/create-tag@v1
   #     with:
    #      version: ${{ steps.version.outputs.content }}
     #     token: ${{ secrets.GITHUB_TOKEN }}
